### ISSUE TITLE
Incompatibility with AdvancedChatHUD when attempting to move ability display

### ISSUE THREAD

**Issue by CringeAura** [Njol/UnofficialMonumentaMod#1]
# Version
1.4.0 for Minecraft 1.17.1

# Brief Description
When attempting to move the ability display by opening chat and dragging the display while having AdvancedChatHUD installed, the ability display refuses to move.

# Steps to Reproduce
1. Install [Unofficial Monumenta Mod](https://www.curseforge.com/minecraft/mc-mods/unofficial-monumenta-mod), [AdvancedChatHUD](https://www.curseforge.com/minecraft/mc-mods/advancedchathud), and [AdvancedChatCore](https://www.curseforge.com/minecraft/mc-mods/advancedchatcore).
2. Open chat.
3. Attempt to drag the ability display.

# Expected Behavior
The ability display moves as intended.

# Actual Behavior
The ability display does not move as the user expects to.

**Comment by Njol** [comment]
Will be fixed in the next version by introducing a new screen to move HUD elements around :)
