### ISSUE TITLE
Mod needs to be updated to support MC 1.19.3

### ISSUE THREAD

**Issue by CringeAura** [Njol/UnofficialMonumentaMod#15]
I noticed you made a comment in the Discord about updating the mod to 1.19.3, so I decided to properly file an issue here. :)

**Comment by Ascynx** [comment]
I have a ported branch in my fork but since I haven't yet made sure everything works fine, the pull request won't be there for a while.

**Comment by Ascynx** [comment]
Will be done with the merge of #16
