### ISSUE TITLE
Mod should be built against at least Fabric Loader ver. 0.12.12 & API ver. 0.42.0

### ISSUE THREAD

**Issue by rinOfTheStars** [Njol/UnofficialMonumentaMod#2]
0.42.0 is the oldest 1.17.1 version of the API _and_ the newest 1.16.5 version of the API, so it should (hopefully) maintain parity across both versions; might be worthwhile to build the 1.17.1 version against the latest 1.17.1 version of the API instead (its mainly just bugfixes and serverside-only feature additions).

Building against Loader version 0.12.12 should always be done with all projects now, as it patches all Log4Shell-related vulns in the Fabric Loader. Due to this, the `fabric.mod.json` file should also enforce  `>=0.12.12` loader version and `>=0.42.0` API version for both 1.16.5 and 1.17.1.

**Comment by Njol** [comment]
Well I guess I've done this with the next version as I was too lazy to test older Fabric versions
