### ISSUE TITLE
Discord Rich Presence Mac Crash

### ISSUE THREAD

**Issue by Alecaboo** [Njol/UnofficialMonumentaMod#27]
After attempting to launch Noelle's Monumenta pack, my game would crash promptly upon startup - after some highly inquisitive searching (I just read the crash log), I found the source of the crash to be UMM's Discord Rich Presence - manually going over to the config file and setting Discord to false solved my launch issue, and the game otherwise runs flawlessly.

I'm attempting to run the game on an Apple Silicon macbook, which I suspect is the cause of the problem, and here's the crash log in case someone is better at understanding them than I am.

[mmCrash.txt](https://github.com/Njol/UnofficialMonumentaMod/files/12634637/mmCrash.txt)

**Comment by Ascynx** [comment]
should be fixed in a future build. Well... fixed, just auto disabling discord rpc, since I don't think the library we are using has an ARM architecture jar.

"Fixed" in 338ef7645d0af75c87a9085cf4eeacc654714508 | 032d3c27b6ca84c52ef27212ebd7086769c16229

**Comment by Ascynx** [comment]
closed by #29 and #30
