### ISSUE TITLE
Black Mist chest counter is broken 

### ISSUE THREAD

**Issue by Looniitick** [Njol/UnofficialMonumentaMod#28]
title
I'm using UMM [1.9.7] for version 1.20.1
- issue might also exist for 1.19.4, as I have seen many players mentioning that it doesn't work
- chest counter shows up either during or after the strike, instead of at the start

**Comment by Ascynx** [comment]
Fixed in 338ef7645d0af75c87a9085cf4eeacc654714508 | 032d3c27b6ca84c52ef27212ebd7086769c16229

**Comment by Ascynx** [comment]
closed by #29 and #30
